name: Build and Publish

on:
  push:
    tags:
      - '*'

permissions:
  contents: read

jobs:
  publish:
    name: Build and Publish
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          # list of Docker images to build
          images: |
            ${{ secrets.DOCKER_HUB_USERNAME }}/yamllint
          # generate Docker tags: X.Y.Z, X.Y, X, latest
          # Note: "latest" is automatically included with type=semver
          tags: |
            type=semver,pattern={{major}}.{{minor}}.{{patch}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Image digest
        run: echo ${{ steps.docker-build.outputs.digest }}

      # See: https://docs.docker.com/build/ci/github-actions/update-dockerhub-desc/
      - name: Update DockerHub description
        uses: peter-evans/dockerhub-description@e98e4d1628a5f3be2be7c231e50981aee98723ae # v4.0.0
        with:
          username: contane
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
          repository: contane/yamllint
          short-description: ${{ github.event.repository.description }}
          enable-url-completion: true
